### ISSUE TITLE
json metadata missing / apiURL

### ISSUE THREAD

**Issue by colin1976** [ashbeech/moralis-mutants-nft-engine#13]
Hi, in your excellent YT video the index.js code differs from the actual Github code.
Extra const are added:
const apiUrl
const apiKey

I reckon const apiKey is my web3 api key. But where can I find my apiURL?
I reckon these parts also do the actual generating of the json metadata files.

**Comment by colin1976** [comment]
solved myself

**Comment by sherlyyan** [comment]
> solved myself

Hi. Could you please share how to find the URL?
Many Thanks!
