### ISSUE TITLE
Generator works great with provided art - any art inputed into the machine doesnt layer, i just get noses

### ISSUE THREAD

**Issue by barnabyjones220** [ashbeech/moralis-mutants-nft-engine#15]
I can go back and add the old moralis art and run the generator, and it works. for some reason when i add my own stuff, it simply defaults to the last layer. 

i know the codes not broken, as it works with original pics. Is anyone else having this issue? no matter how i modify the art, once i export it as a jpg, it has a white background and thats all that exists in the last layer.

**Comment by J-Renegade** [comment]
When I had this issue it was only displaying the last layer compiled into the layered file because the the individual layers weren't on transparent backgrounds. Once I generated the project after replacing the original files with transparent background files it worked great.

**Comment by barnabyjones220** [comment]
Thanks! I actually ended up fixing this with that exact thing. I had exported all my files to a jpg assuming that would be fine, but oh no. you must export your files to a PNG, with transparency and no trim, so it shows up as the right layer, and in the right position. 

Hope this helps someone else!
