### ISSUE TITLE
XAPI Key not working

### ISSUE THREAD

**Issue by zohairhadi** [ashbeech/moralis-mutants-nft-engine#8]
Hello,
I can't seem to find the XAPI key. How am I supposed to operate the Swagger to get my API key?

Help would be greatly appreciated

**Comment by mikecann** [comment]
Agreed, im not sure on this part.. Following https://deep-index.moralis.io/api-docs/#/storage/uploadFolder and clicking execute as in the video just errors: 

![image](https://user-images.githubusercontent.com/215033/148665290-83314392-c099-44cf-b89b-1dd390abefca.png)

**Comment by mikecann** [comment]
The video says that you should be authorized but there is no info on how exactly to do that.. 

![image](https://user-images.githubusercontent.com/215033/148665542-bf63c5de-e41e-4d9a-81fa-acf5d96532c6.png)

**Comment by mikecann** [comment]
Okay I worked it out, the api key is this: 

![image](https://user-images.githubusercontent.com/215033/148665602-31e48c5a-955d-4cb3-9d26-559f491a099c.png)

You dont need to go to https://deep-index.moralis.io/api-docs/#/storage/uploadFolder at all, just use that

**Comment by zohairhadi** [comment]
Yep, this works. Great find.
Thank you!
